### ISSUE TITLE
Adaptive IHS

### ISSUE THREAD

**Issue by wasim419** [sjtrny/FuseBox#1]
Hi dear all.....I am a masters student...... I need a matlab code for Adaptive IHS..... the paper for this topic is "An Adaptive IHS Pan-Sharpening Method"..... Really thankful to you for help...

**Comment by sjtrny** [comment]
Hi wasim419, we have implemented Adaptive IHS for you! Take a look at the IHS folder https://github.com/sjtrny/FuseBox/tree/master/ihs_pansharp.

Closing.

**Comment by wasim419** [comment]
Hi sir, this code is just simple IHS..... i need a code for the paper i mentioned here.... the code in the paper mentioned is used to remove spectral distorsion.... or if you have any other code to remove spectral distorsion then i will be really thankful to you for that... i really need that....waiting for your reply
